### ISSUE TITLE
ActionController::RoutingError (No route matches [POST] "/scheduled"):

### ISSUE THREAD

**Issue by cavebring** [tawan/active-elastic-job#113]
Hi,
When I run scheduled job, like:

`ReportMetricEvent.set(wait: 10.minutes).perform_later(title: "Account Maintanance", text: "Updated!", alert_type: 'success')`

Then SQS do posts to /scheduled it seems but active-elastic-job don't pick that up.

Is this a bug or something I am missing?

Raw:
```
F, [2020-07-11T13:34:03.089458 #20868] FATAL -- : 
ActionController::RoutingError (No route matches [POST] "/scheduled"):
  actionpack (4.2.11.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  rollbar (2.26.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.11.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.2.11.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.13) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.13) lib/rack/runtime.rb:18:in `call'
  rack (1.6.13) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.11.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.11.1) lib/rails/application.rb:165:in `call'
  rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
  puma (4.3.5) lib/puma/configuration.rb:228:in `call'
  puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
  puma (4.3.5) lib/puma/server.rb:472:in `process_client'
  puma (4.3.5) lib/puma/server.rb:328:in `block in run'
  puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by joeyparis** [comment]
I'm not sure why your SQS would be posting to `/scheduled`, but the default is `/periodic_tasks`. You can override this setting though with `config.active_elastic_job.periodic_tasks_route = '/scheduled'`. Hopefully, that helps! I am going to close this issue for now, but if you aren't able to get it working with the config update, feel free to open it back up!
