### ISSUE TITLE
How to find out why a job failed?

### ISSUE THREAD

**Issue by karensg** [tawan/active-elastic-job#24]
Hi Tawan,

I am using your library for a month already and so far it works really smooth. Thanks a lot for that.

I have some issues debugging why the jobs are failing on the worker. I noticed that a message ended up in a dead queue, so I tried to resend it. That failed. Usually I get an error from [AppSignal](https://appsignal.com/). But this time - nothing. Then I tried to take a look in the EB logs:

**/var/log/aws-sqsd/default.log**
```
2016-03-13T17:33:56Z message: sent to %[http://localhost:80]
2016-03-13T17:33:56Z http-err: f0d021e8-cde9-413f-aafc-e1a02a523912 (1) 403 - 0.004
2016-03-13T19:03:13Z message: sent to %[http://localhost:80]
2016-03-13T19:04:24Z message: sent to %[http://localhost:80]
2016-03-13T19:04:24Z message: sent to %[http://localhost:80]
2016-03-13T19:59:59Z message: sent to %[http://localhost:80]
2016-03-13T19:59:59Z http-err: 5ba003c1-b275-4582-841f-f73024f94a6c (1) 403 - 0.004
```
Not sure if this one is relevant but in **var\log\cfn-hup.log** I get lots of these:
```
2016-03-13 20:35:05,351 [DEBUG] Receiving messages for queue https://eu-central-1.queue.amazonaws.com/45051790cxxx/xxxxf0ab5de7d1b20a6692967bcb1cb79d8b8d8b
2016-03-13 20:35:05,416 [ERROR] IOError caught while processing messages
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/update_hooks.py", line 407, in process
    for msg in self.sqs_client.receive_message(self.queue_url, request_credentials = self._creds_provider.credentials, wait_time=20):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 181, in _retry
    raise last_error
AwsQueryError: [Errno 403] RequestThrottled: Your ReceiveMessage request is throttled because you have too many concurrent ReceiveMessage requests coming from your account.  Reduce the number of clients polling your queues.
2016-03-13 20:35:05,416 [DEBUG] Receiving messages for queue https://eu-central-1.queue.amazonaws.com/45051790cxxx/xxxxf0ab5de7d1b20a6692967bcb1cb79d8b8d8b
2016-03-13 20:35:05,481 [ERROR] IOError caught while processing messages
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/update_hooks.py", line 407, in process
    for msg in self.sqs_client.receive_message(self.queue_url, request_credentials = self._creds_provider.credentials, wait_time=20):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/util.py", line 181, in _retry
    raise last_error
```

Do you have any advice how I can find out what happened?

**Comment by zaaroth** [comment]
How many servers do you have in your worker pool?

**Comment by karensg** [comment]
It is a single instance.

**Comment by tawan** [comment]
Can you post the `HTTP connections` setting from your worker environment configuration?

**Comment by karensg** [comment]
It is at default setting (10)
![capture](https://cloud.githubusercontent.com/assets/359682/13743597/096ac04e-e9e3-11e5-82a8-ee4c7da865cb.PNG)

**Comment by zaaroth** [comment]
What about the queue configuration?

**Comment by karensg** [comment]
![sqs](https://cloud.githubusercontent.com/assets/359682/13769995/4500b432-ea84-11e5-96af-4c00c7424afb.PNG)
I have put maximum recievs to 1 to prevent that emails get sent several times

**Comment by zaaroth** [comment]
Did you figure this out, @karensg ?

**Comment by karensg** [comment]
No unfortunately I did not. After that occurrence, I did not have any failed messages again.
I think I will need to dig in to the [custom monitoring with AppSingal.](http://docs.appsignal.com/background-monitoring/custom.html). Somehow the default configuration did not track that error.

You can close the issue though :)
