### ISSUE TITLE
ActiveJob::QueueAdapters::ActiveElasticJobAdapter::NonExistentQueue when Mailer

### ISSUE THREAD

**Issue by fguillen** [tawan/active-elastic-job#65]
I have configured the `active-elastic-job` gem properly to manage ActiveJobs, and it works.

But when I try to send a `ActionMailer.deliver_later` it tries to use a Queue that is not existing: 

    production-mailer

This is what I have in the `/config/environments/production.rb`: 

    config.active_job.queue_adapter = :active_elastic_job
    config.active_job.queue_name_prefix = Rails.env
    config.active_job.queue_name_delimiter = "-"
    config.active_job.queue_name = Proc.new { "surveyplatform-activejobs" }
    config.active_elastic_job.process_jobs = ENV["PROCESS_ACTIVE_ELASTIC_JOBS"] == "true"
    config.active_elastic_job.aws_credentials = lambda { Aws::InstanceProfileCredentials.new } # allows lambdas for lazy loading
    config.active_elastic_job.secret_key_base = Rails.application.secrets[:secret_key_base]

Stack trace:

```
F, [2017-06-02T16:22:47.180826 #20273] FATAL -- : [2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] ActiveJob::QueueAdapters::ActiveElasticJobAdapter::NonExistentQueue (            The job is bound to queue at production-mailers.
            Unfortunately a queue with this name does not exist in this
            region. Either create an Amazon SQS queue named production-mailers -
            you can do this in AWS console, make sure to select region
            '' - or you
            select another queue for your jobs.
):
F, [2017-06-02T16:22:47.180852 #20273] FATAL -- : [2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1]   
F, [2017-06-02T16:22:47.180902 #20273] FATAL -- : [2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] active_elastic_job (2.0.1) lib/active_job/queue_adapters/active_elastic_job_adapter.rb:144:in `rescue in queue_url'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] active_elastic_job (2.0.1) lib/active_job/queue_adapters/active_elastic_job_adapter.rb:138:in `queue_url'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] active_elastic_job (2.0.1) lib/active_job/queue_adapters/active_elastic_job_adapter.rb:121:in `build_message'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] active_elastic_job (2.0.1) lib/active_job/queue_adapters/active_elastic_job_adapter.rb:95:in `enqueue_at'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] active_elastic_job (2.0.1) lib/active_job/queue_adapters/active_elastic_job_adapter.rb:89:in `enqueue'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] active_elastic_job (2.0.1) lib/active_job/queue_adapters/active_elastic_job_adapter.rb:80:in `enqueue'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/enqueuing.rb:76:in `block in enqueue'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:126:in `call'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/logging.rb:15:in `block (3 levels) in <module:Logging>'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/logging.rb:44:in `block in tag_logger'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/logging.rb:44:in `tag_logger'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/logging.rb:14:in `block (2 levels) in <module:Logging>'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:391:in `instance_exec'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:391:in `block in make_lambda'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:285:in `block in halting'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:447:in `block in around'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_enqueue_callbacks'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/enqueuing.rb:72:in `enqueue'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] activejob (5.0.2) lib/active_job/configured_job.rb:13:in `perform_later'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:121:in `enqueue_delivery'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] actionmailer (5.0.2) lib/action_mailer/message_delivery.rb:76:in `deliver_later'
[2017-06-02 16:22:37.844] [07684ef6] [0000000] [127.0.0.1] lib/dalia/survey_platform/survey_data_extraction/runner.rb:45:in `notify_user'

```

**Comment by einzige** [comment]
config.active_elastic_job.aws_region = 'your region'

**Comment by fguillen** [comment]
@einzige thanks, it is working I suggest to add something in the README.
