### ISSUE TITLE
Message Verification with Rails 5.2

### ISSUE THREAD

**Issue by youngbrioche** [tawan/active-elastic-job#87]
After upgrading to Rails 5.2 we're seeing 

```
TypeError: no implicit conversion of nil into String
  from active_elastic_job/message_verifier.rb:31:in `hexdigest'
  from active_elastic_job/message_verifier.rb:31:in `generate_digest'
  from active_job/queue_adapters/active_elastic_job_adapter.rb:189:in `message_digest'
  from active_job/queue_adapters/active_elastic_job_adapter.rb:126:in `build_message'
  from active_job/queue_adapters/active_elastic_job_adapter.rb:95:in `enqueue_at'
  from active_job/queue_adapters/active_elastic_job_adapter.rb:89:in `enqueue'
  from active_job/queue_adapters/active_elastic_job_adapter.rb:80:in `enqueue'
  from active_job/enqueuing.rb:53:in `block in enqueue'
  from active_support/callbacks.rb:109:in `block in run_callbacks'
  from active_job/logging.rb:17:in `block (3 levels) in <module:Logging>'
  from active_job/logging.rb:46:in `block in tag_logger'
  from active_support/tagged_logging.rb:71:in `block in tagged'
  from active_support/tagged_logging.rb:28:in `tagged'
  from active_support/tagged_logging.rb:71:in `tagged'
  from active_job/logging.rb:46:in `tag_logger'
  from active_job/logging.rb:16:in `block (2 levels) in <module:Logging>'
  from active_support/callbacks.rb:118:in `instance_exec'
  from active_support/callbacks.rb:118:in `block in run_callbacks'
  from active_support/callbacks.rb:136:in `run_callbacks'
  from active_job/enqueuing.rb:49:in `enqueue'
  from active_job/enqueuing.rb:20:in `perform_later'
  from backgrounder/support/backends.rb:26:in `enqueue_active_job'
  from backgrounder/support/backends.rb:20:in `enqueue_for_backend'
  from backgrounder/orm/base.rb:112:in `enqueue_file_background_job'
  from active_support/callbacks.rb:426:in `block in make_lambda'
  from active_support/callbacks.rb:261:in `block in conditional'
  from active_support/callbacks.rb:517:in `block in invoke_after'
  from active_support/callbacks.rb:517:in `each'
  from active_support/callbacks.rb:517:in `invoke_after'
  from active_support/callbacks.rb:133:in `run_callbacks'
  from active_support/callbacks.rb:816:in `_run_commit_callbacks'
  from active_record/transactions.rb:345:in `committed!'
  from active_record/connection_adapters/abstract/transaction.rb:119:in `commit_records'
  from active_record/connection_adapters/abstract/transaction.rb:214:in `block in commit_transaction'
  from monitor.rb:226:in `mon_synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:204:in `commit_transaction'
  from active_record/connection_adapters/abstract/transaction.rb:243:in `block in within_new_transaction'
  from monitor.rb:226:in `mon_synchronize'
  from active_record/connection_adapters/abstract/transaction.rb:227:in `within_new_transaction'
  from active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
  from active_record/transactions.rb:212:in `transaction'
  from active_record/transactions.rb:383:in `with_transaction_returning_status'
  from active_record/transactions.rb:310:in `block in save'
  from active_record/transactions.rb:325:in `rollback_active_record_state!'
  from active_record/transactions.rb:309:in `save'
  from active_record/suppressor.rb:44:in `save'
…
```

in all of our jobs. Looks like something changed within message verification:

```ruby
# new_framework_defaults_5_2.rb

# Use AES-256-GCM authenticated encryption as default cipher for encrypting messages
# instead of AES-256-CBC, when use_authenticated_message_encryption is set to true.
# Rails.application.config.active_support.use_authenticated_message_encryption = true
```

Setting this to either `true` or `false` has no effect, the exception remains.

**Comment by snovotny** [comment]
It appears this has to do with how the `secret_key_base` is set.  We have a vanilla Rails 5.2 app and it was showing that config value was `nil`; adding this to an initializer got the queuing to work:

```ruby
Rails.application.config.active_elastic_job.secret_key_base = Rails.application.credentials.secret_key_base
```
